# Generated by Django 5.2.9 on 2026-02-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=32)),
                ('race_ethnicity', models.CharField(max_length=50)),
                ('parental_level_of_education', models.CharField(max_length=50)),
                ('lunch', models.CharField(max_length=32)),
                ('test_preparation_course', models.CharField(max_length=50)),
                ('reading_score', models.IntegerField()),
                ('math_score', models.IntegerField()),
            ],
        ),
    ]
